# Generated by Django 3.2.8 on 2021-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211122_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='display_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
