# Generated by Django 3.2.8 on 2021-11-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_module_display_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='display_number',
        ),
    ]
