# Generated by Django 3.2.8 on 2022-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_usercustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='id_for_roman',
            field=models.CharField(default='', max_length=255),
        ),
    ]
