# Generated by Django 3.2.8 on 2022-01-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_module_id_for_roman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id_for_roman',
        ),
    ]
